export const homeObjOne = {
  id: 'información',
  lightBg: false,
  lightText: true,
  topLine: 'Centro Preparador Oficial de Cambridge.',
  headline: 'Buscamos nuevos alumnos para aprender inglés.',
  description: 'Damos cursos, clases grupales, preparamos para el examen SLP del ejército y de la guardia civil, Aptis y por supuesto, como centro preparador oficial que somos, Cambridge, desde nivel A1 hasta nivel C2.',
  buttonLabel: 'Apúntate',
  imgStart: false,
  img: require('../../Images/B1withenglish.jpg'),
  alt: 'Logotipo',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'campus',
  lightBg: true,
  LighTextDesc: true,
  topLine: 'Nuestro campus virtual cuenta con más de 500 ejercicios.',
  headline: 'Diseñamos un plan de estudios a medida según tus necesidades.',
  description: 'Para que aprendas el máximo posible no solo utilizamos planes de estudio personalizados, aplicaciones gratuitas de asistencia al estudio y nuestro campus virtual, también estamos desarrollando nuestra propia app para que el estudio se adapte mejor a ti.',
  buttonLabel: 'Apúntate',
  imgStart: true,
  img: require('../../Images/ipad.png'),
  alt: 'Ipad con imagen del campus virtual',
  dark: true,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'info3',
  lightBg: false,
  lightText: true,
  topLine: 'Nuestro objetivo: Que apruebes el exámen y que aprendas de verdad en el proceso.',
  headline: 'Las clases siempre son de tamaño reducido para dar la mejor calidad posible.',
  description: 'Las clases tendrán como máximo 5 alumnos y los cursos nunca, bajo ningún concepto, superarán los 10 alumnos.',
  buttonLabel: 'Apúntate',
  imgStart: false,
  img: require('../../Images/Teamwork.jpg'),
  alt: 'Alumnos trabajando en equipo',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: 'campus',
  lightBg: true,
  LighTextDesc: true,
  topLine: 'Estamos aquí para ayudarte.',
  headline: 'Pregúntanos lo que necesites, sin ningún tipo de compromiso.',
  description: 'Puedes contactarnos en la Calle Ganado Nº23 1ºD, a través de nuestras redes sociales, número de teléfono o mediante otras formas que te dejamos más abajo.',
  buttonLabel: 'Contáctanos',
  imgStart: true,
  img: require('../../Images/Sitio.PNG'),
  alt: 'Localización del negocio',
  dark: true,
  primary: false,
  darkText: true,
};